name: APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  apk:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Changement des permissions pour l'executable
        run: chmod +x ./gradlew

      - name: Creation de l'APK
        run: ./gradlew assembleDebug

      - name: Publication de l'APK en tant qu'artefact
        uses: actions/upload-artifact@v3
        with:
          name: APK-debug
          path: app/build/outputs/apk/debug/